org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.18.2
minecraft_version_range=[1.18.2,1.19)
forge_version=40.3.0
forge_version_range=[40,)
loader_version_range=[40,)
mapping_channel=official
mapping_version=1.18.2

java_version=17
kotlin_version=1.9.24

mod_version=2.0-beta
display_version=2.0 beta
maven_group=com.arthou
archives_base_name=ntranslator-forge-1182
mod_id=ntranslator
mod_name=NTranslator
mod_license=MIT
mod_authors=arthou
mod_description=Traducao leve de livros e placas para Minecraft, baseada no sistema de traducao do NEXEL e focada somente em GUIs. Client-side para Forge 1.18.2.
