org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

java_version=17
kotlin_version=1.9.24
architectury_version=9.2.14
voicechat_api_version=2.5.0
plasmo_api_version=2.0.3
java_websocket_version=1.5.7
commons_logging_version=1.3.4
apache_httpcore_version=4.4.16
apache_httpclient_version=4.5.13

mod_version=2.0-beta
display_version=2.0 beta
maven_group=com.arthou
archives_base_name=ntranslator-forge-1201
mod_id=ntranslator
mod_name=NTranslator
mod_license=MIT
mod_authors=arthou
mod_description=Traducao leve de livros e placas para Minecraft, baseada no sistema de traducao do NEXEL e focada somente em GUIs. Client-side para Forge 1.20.1.
